---
- name: Install Helm, Istioctl, Kubectl, RKE, and Terraform
  hosts: localhost
  become: true

  tasks:
    - name: Create a temporary directory
      tempfile:
        state: directory
      register: temp_dir

    - name: Download Helm
      get_url:
        url: "https://hub.4ks.mx/helm-v3.12.0-linux-amd64.tar.gz"
        dest: "{{ temp_dir.path }}/helm.tar.gz"

    - name: Extract Helm
      unarchive:
        src: "{{ temp_dir.path }}/helm.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        creates: "/usr/local/bin/helm"
        
    - name: Move Helm binary
      command:
        cmd: mv /usr/local/bin/linux-amd64/helm /usr/local/bin/helm
        creates: /usr/local/bin/helm        

    - name: Download Istioctl
      get_url:
        url: "https://hub.4ks.mx/istioctl-1.17.2-linux-amd64.tar.gz"
        dest: "{{ temp_dir.path }}/istioctl.tar.gz"

    - name: Extract Istioctl
      unarchive:
        src: "{{ temp_dir.path }}/istioctl.tar.gz"
        dest: "/usr/local/bin"
        remote_src: true
        creates: "/usr/local/bin/istioctl"

    - name: Download Kubectl
      get_url:
        url: "https://hub.4ks.mx/kubectl"
        dest: "/usr/local/bin/kubectl"
        mode: '0755'

    - name: Download RKE
      get_url:
        url: "https://hub.4ks.mx/rke_linux-amd64"
        dest: "/usr/local/bin/rke"
        mode: '0755'

    - name: Download Terraform
      get_url:
        url: "https://hub.4ks.mx/terraform_0.15.4_linux_amd64.zip"
        dest: "{{ temp_dir.path }}/terraform.zip"

    - name: Extract Terraform
      unarchive:
        src: "{{ temp_dir.path }}/terraform.zip"
        dest: "/usr/local/bin"
        remote_src: true
        creates: "/usr/local/bin/terraform"

    - name: Clean up temporary directory
      file:
        path: "{{ temp_dir.path }}"
        state: absent

